"""
ai_agent/report_generator.py
-----------------------------
Generates comprehensive threat analysis reports using Ollama + DB data.
"""

import sqlite3
from datetime import datetime
from utils.logger import get_logger

logger = get_logger("ai_agent.report_generator")


class ReportGenerator:
    """Generates structured threat intelligence reports."""

    async def generate(self) -> str:
        """Pull DB data and generate a full markdown report."""
        stats = self._gather_stats()
        report_md = self._format_report(stats)
        return report_md

    def _gather_stats(self) -> dict:
        conn = sqlite3.connect("spectrum.db")
        cur = conn.cursor()

        cur.execute("SELECT label, COUNT(*), AVG(confidence) FROM signals GROUP BY label")
        by_label = {r[0]: {"count": r[1], "avg_conf": r[2] or 0} for r in cur.fetchall()}

        cur.execute("SELECT COUNT(*) FROM signals WHERE timestamp >= datetime('now', '-24 hours')")
        last_24h = cur.fetchone()[0]

        cur.execute("SELECT COUNT(*) FROM alerts")
        alert_total = cur.fetchone()[0]

        cur.execute("SELECT * FROM signals WHERE label != 'Normal' ORDER BY confidence DESC LIMIT 10")
        top_threats = cur.fetchall()

        conn.close()
        return {
            "by_label": by_label,
            "last_24h": last_24h,
            "alert_total": alert_total,
            "top_threats": top_threats,
            "generated_at": datetime.now().isoformat(),
        }

    def _format_report(self, stats: dict) -> str:
        lines = [
            f"# Spectrum Threat Intelligence Report",
            f"**Generated:** {stats['generated_at']}",
            f"**System:** AI-Powered Spectrum Anomaly Detection v2.0",
            "",
            "---",
            "",
            "## Executive Summary",
            f"The system has processed **{sum(v['count'] for v in stats['by_label'].values())} signals**.",
            f"**{stats['last_24h']} signals** were recorded in the last 24 hours.",
            f"**{stats['alert_total']} alerts** were triggered in total.",
            "",
            "## Signal Distribution",
        ]

        for label, data in stats["by_label"].items():
            lines.append(f"- **{label}**: {data['count']} signals (avg confidence: {data['avg_conf']:.1%})")

        lines += [
            "",
            "## Threat Assessment",
        ]

        anomaly_count = sum(v["count"] for k, v in stats["by_label"].items() if k != "Normal")
        total = sum(v["count"] for v in stats["by_label"].values()) or 1

        if anomaly_count == 0:
            lines.append("✅ **No anomalies detected.** System operating within normal parameters.")
        elif anomaly_count / total < 0.1:
            lines.append(f"⚠️ **Low threat level.** {anomaly_count} anomalies detected ({anomaly_count/total:.1%} of signals).")
        else:
            lines.append(f"🔴 **ELEVATED THREAT LEVEL.** {anomaly_count} anomalies detected ({anomaly_count/total:.1%} of signals).")

        lines += [
            "",
            "## Recommendations",
            "1. Monitor high-confidence anomaly signals for pattern analysis",
            "2. Cross-reference detected drone frequencies with approved UAV operators",
            "3. Implement adaptive notch filtering for identified jamming frequencies",
            "4. Review alert thresholds and escalation procedures",
            "5. Update AI model with new labeled samples for improved accuracy",
            "",
            "---",
            "*Report generated by SpectrumAI Agent | ITC Egypt Spectrum Defense System*",
        ]

        return "\n".join(lines)
