"""dashboard/pages/reports.py - AI-generated threat intelligence reports."""
import streamlit as st
from datetime import datetime
from dashboard.api_client import APIClient


def render():
    st.markdown("""
    <div class="page-header">
        <h1 class="page-title">📄 Reports</h1>
        <p class="page-subtitle">AI-generated threat intelligence reports</p>
    </div>
    """, unsafe_allow_html=True)

    client = APIClient()

    col1, _ = st.columns([1, 3])
    with col1:
        generate = st.button("🤖 Generate AI Report", type="primary", use_container_width=True)

    if generate:
        with st.spinner("Generating threat intelligence report..."):
            result = client.get_report()

        if result:
            report_md = result.get("report", "")
            generated_at = result.get("generated_at", datetime.now().isoformat())

            st.markdown(f"""
            <div class="report-header">
                <span>📋 Threat Intelligence Report</span>
                <span class="report-meta">Generated: {generated_at[:19]}</span>
            </div>
            """, unsafe_allow_html=True)

            st.markdown('<div class="report-body">', unsafe_allow_html=True)
            st.markdown(report_md)
            st.markdown('</div>', unsafe_allow_html=True)

            # Download buttons
            c1, c2 = st.columns(2)
            with c1:
                st.download_button("⬇ Download Markdown", report_md, "spectrum_report.md", "text/markdown")
            with c2:
                st.download_button("⬇ Download TXT", report_md, "spectrum_report.txt", "text/plain")
        else:
            st.error("Failed to generate report. Check API connection.")
    else:
        st.markdown("""
        <div class="info-banner">
            <div class="info-banner-icon">💡</div>
            <div>
                <strong>AI-Powered Report Generation</strong><br>
                Click "Generate AI Report" to create a comprehensive threat intelligence report
                analyzing all detected signals, anomalies, and recommended actions.
                The report is generated by the SpectrumAI agent using your live database.
            </div>
        </div>
        """, unsafe_allow_html=True)
